language: java
jdk:
  - oraclejdk8
script: 
  - mvn clean install nbm:autoupdate
  - cd target/netbeans_site && zip -r nbscala-plugins.zip *.nbm
deploy:
  provider: releases
  api_key: "$GH_TOKEN"
  file: "$HOME/build/$TRAVIS_REPO_SLUG/target/netbeans_site/nbscala-plugins.zip"
  skip_cleanup: true
  on:
    tags: true
